# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyForm(object):
    def setupUi(self, MyForm):
        MyForm.setObjectName("MyForm")
        MyForm.setEnabled(True)
        MyForm.resize(400, 300)
        self.pushButton = QtWidgets.QPushButton(MyForm)
        self.pushButton.setGeometry(QtCore.QRect(130, 150, 100, 32))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(MyForm)
        self.label.setGeometry(QtCore.QRect(140, 90, 91, 16))
        self.label.setObjectName("label")

        self.retranslateUi(MyForm)
        QtCore.QMetaObject.connectSlotsByName(MyForm)

    def retranslateUi(self, MyForm):
        _translate = QtCore.QCoreApplication.translate
        MyForm.setWindowTitle(_translate("MyForm", "My first form"))
        self.pushButton.setText(_translate("MyForm", "Greeting"))
        self.label.setText(_translate("MyForm", "There will text"))
